// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "BORG_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// checkIndexOverlap
List checkIndexOverlap(IntegerVector train_idx, IntegerVector test_idx);
RcppExport SEXP _BORG_checkIndexOverlap(SEXP train_idxSEXP, SEXP test_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type train_idx(train_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type test_idx(test_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(checkIndexOverlap(train_idx, test_idx));
    return rcpp_result_gen;
END_RCPP
}
// checkDuplicateRows
List checkDuplicateRows(NumericMatrix data, IntegerVector train_idx, IntegerVector test_idx);
RcppExport SEXP _BORG_checkDuplicateRows(SEXP dataSEXP, SEXP train_idxSEXP, SEXP test_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type train_idx(train_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type test_idx(test_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(checkDuplicateRows(data, train_idx, test_idx));
    return rcpp_result_gen;
END_RCPP
}
// checkTemporalOrder
List checkTemporalOrder(NumericVector timestamps, IntegerVector train_idx, IntegerVector test_idx);
RcppExport SEXP _BORG_checkTemporalOrder(SEXP timestampsSEXP, SEXP train_idxSEXP, SEXP test_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type timestamps(timestampsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type train_idx(train_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type test_idx(test_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(checkTemporalOrder(timestamps, train_idx, test_idx));
    return rcpp_result_gen;
END_RCPP
}
// checkGroupOverlap
List checkGroupOverlap(IntegerVector groups, IntegerVector train_idx, IntegerVector test_idx);
RcppExport SEXP _BORG_checkGroupOverlap(SEXP groupsSEXP, SEXP train_idxSEXP, SEXP test_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type train_idx(train_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type test_idx(test_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(checkGroupOverlap(groups, train_idx, test_idx));
    return rcpp_result_gen;
END_RCPP
}
// computeCorrelation
double computeCorrelation(NumericVector x, NumericVector y);
RcppExport SEXP _BORG_computeCorrelation(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(computeCorrelation(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BORG_checkIndexOverlap", (DL_FUNC) &_BORG_checkIndexOverlap, 2},
    {"_BORG_checkDuplicateRows", (DL_FUNC) &_BORG_checkDuplicateRows, 3},
    {"_BORG_checkTemporalOrder", (DL_FUNC) &_BORG_checkTemporalOrder, 3},
    {"_BORG_checkGroupOverlap", (DL_FUNC) &_BORG_checkGroupOverlap, 3},
    {"_BORG_computeCorrelation", (DL_FUNC) &_BORG_computeCorrelation, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BORG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
