# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkIndexOverlap <- function(train_idx, test_idx) {
    .Call(`_BORG_checkIndexOverlap`, train_idx, test_idx)
}

checkDuplicateRows <- function(data, train_idx, test_idx) {
    .Call(`_BORG_checkDuplicateRows`, data, train_idx, test_idx)
}

checkTemporalOrder <- function(timestamps, train_idx, test_idx) {
    .Call(`_BORG_checkTemporalOrder`, timestamps, train_idx, test_idx)
}

checkGroupOverlap <- function(groups, train_idx, test_idx) {
    .Call(`_BORG_checkGroupOverlap`, groups, train_idx, test_idx)
}

computeCorrelation <- function(x, y) {
    .Call(`_BORG_computeCorrelation`, x, y)
}

